name: modern_pageable_listview
description: >
  Modren Pageable ListView, simple implementation showcase repository.
  - flutter
  - bloc
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  logging: ^1.2.0
  result_dart: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  zoo_lints: ^3.0.0

flutter:
  uses-material-design: true
